### ISSUE TITLE
"Western" is nebulous

### ISSUE THREAD

**Issue by MostAwesomeDude** [nixos-users-for-western-mil-and-govs/NixOS-Users-For-Western-MIL-And-GOVs.github.io#3]
Did you mean "NATO"?

**Comment by mrkline** [comment]
I don't want to speak for @maxkokocom, but I wouldn't draw the circle that narrowly. It *is* a bit nebulous, but colloquially it usually refers to countries with the Enlightenment values Max listed (liberal democracy, rule of law, freedom of expression, etc.) I'd certainly include non-NATO countries like Australia, Japan, Korea, Taiwan...

**Comment by maxkokocom** [comment]
Yes, nebulous is correct, as it doesn't have to be NATO to share Western values. Many countries chose neutrality, such as Switzerland, historically Finland/Sweden, which just recently changed their mind. Poland, being a big NATO country now, just recently was a member of the Warsaw Pact with the Soviets, and it was also not certain they would join NATO, but cerain they wanted to be a culture respecting western values. Neutrality like Finland/Sweden was also considered. 

Many countries in South America also aim for those to be part of their life, as well as the non-NATO in Asia mentioned by @mrkline , I know them less so I don't want to claim expertise on their internal ethics and values systems journey.

There are plenty of different pathways each society can choose. What's important is that they can indeed make this choice, and you can make an argument that NATO helps to make sure such a choice exists in the first place.
