### ISSUE TITLE
This is the stupidest thing i've ever read

### ISSUE THREAD

**Issue by adryzz** [nixos-users-for-western-mil-and-govs/NixOS-Users-For-Western-MIL-And-GOVs.github.io#5]
https://github.com/nixos-users-for-western-mil-and-govs/NixOS-Users-For-Western-MIL-And-GOVs.github.io/blob/bc146a2adbe23e9a0e33bec8a1f0966738abd26b/src/index.md?plain=1#L11-L18

this is absolutely not true. in fact, it does not and has not defended in the past civil liberties, women's rights, democratic governance, rule of law and equality under the law.

Assuming that by "western" you mean US and NATO, those are all things that [have not been defended in the past](https://en.wikipedia.org/wiki/American_imperialism), and that are not defended now. Turns out that showering kids on the other side of the globe with napalm [did not, in fact protect their human rights](https://en.wikipedia.org/wiki/United_States_war_crimes).

And the US military boasted [7000+ reported sexual assaults in 2019](https://www.defense.gov/Explore/News/Article/Article/2172056/defense-officials-tout-progress-in-fight-against-sexual-assault/), an increase of ***3%*** from the previous year.

I feel like it's very hypocritical to say you "protect basic human rights" in other countries, when those basic human rights aren't even protected or taken seriously in your home country. [But what do i know...](https://en.wikipedia.org/wiki/Border_search_exception)

Defending *War Crimes As A Service* (***WCaaS***) providers at all costs in the name of an ideological "free speech", serves no purpose other than western imperialism. If you like bombing kids on the other side of the globe, there's no point in pretending to care about civil rights, just say so.

**Comment by maxkokocom** [comment]
You assume I am blind to western imperialim issues. I simply would choose all of those issues and being a mortgage slave of western imperialism anyday whether its British/American/Next_One rather then contenders empires as someone born few years after Soviet union collapse in a Warsaw Pact country. 

Happy to disagree tho. Clearly you are happy with the Open Letter that started this disscusion.

**Comment by adryzz** [comment]
>  simply would choose all of those issues and being a mortgage slave of western imperialism anyday

Easy to say sitting on your comfortable chair, not being impacted by any of the aforementioned. But i guess to each their priorities...

**Comment by maxkokocom** [comment]
I fully agree that it's easy to say. I hope more people will be in a Western country where it is so easy to say. My country has become Western, and I am very happy about it. It could end up like Ukraine ended up today if we kept to corrupted authoritarian post-Soviet traditions rather than push strongly for becoming a Western free society.

**Comment by K4rakara** [comment]
The creator of this repository is a clown lmao :clown_face:
